name: Deploy the WebSocket
on:
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.websocket
          push: true
          tags: acidop/drawdeck-ws:${{ github.sha }}
          
      # VM Deployment (Commented out)
      # - name: Deploy to VM
      #   uses: appleboy/ssh-action@v1.1.0
      #   with:
      #     host: ${{ secrets.VM_HOST }}
      #     username: ${{ secrets.VM_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       sudo docker pull acidop/drawdeck-ws:${{ github.sha }}
      #       sudo docker stop ws-server || true
      #       sudo docker rm ws-server || true
      #       sudo docker run -d \
      #         --name ws-server \
      #         --restart always \
      #         -p 8080:8080 \
      #         acidop/drawdeck-ws:${{ github.sha }}
